[package]
name = "gmkcf"
version = "0.0.0"
edition = "2024"
author = "Krishna Kushwaha"

[dependencies]
actix-web = { version = "4.5.1", optional = true }
actix-multipart = { version = "0.7.2", optional = true }
futures-util = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
anyhow = "1.0.80"
thiserror = "1.0.57"
env_logger = { version = "0.11.3", optional = true }
log = "0.4.21"

# Crypto
chacha20poly1305 = "0.10.1"
x25519-dalek = { version = "2.0.1", features = ["static_secrets", "serde"] }
rand = "0.8.5"
hex = "0.4.3"
base64 = "0.22.0"

# Binary Format
byteorder = "1.5.0"

[[bin]]
name = "gmkcf"
path = "src/bin/gmkcf.rs"
required-features = ["server"]

[features]
default = []
server = ["dep:actix-web", "dep:actix-multipart", "dep:env_logger"]
